/*
   Copyright 2026 The ARCORIS Authors.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

package importtest

import (
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const (
	rootImport = "arcoris.dev/arclog"
	apiImport  = rootImport + "/api/"
)

func TestAPIPackagesRespectImportBoundaries(t *testing.T) {
	t.Parallel()

	apiDir := filepath.Join(repoRoot(t), "api")
	err := filepath.WalkDir(apiDir, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			if entry.Name() == "testdata" || entry.Name() == "vendor" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") || isGeneratedGoFile(path) {
			return nil
		}

		checkFileImports(t, apiDir, path)
		return nil
	})
	if err != nil {
		t.Fatalf("walk api imports: %v", err)
	}
}

func TestForbiddenImportReasonDocumentsPackageRules(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name       string
		pkgPath    string
		testFile   bool
		importPath string
		wantReason string
	}{
		{
			name:       "api package cannot import root facade",
			pkgPath:    "core",
			importPath: rootImport,
			wantReason: "root facade",
		},
		{
			name:       "runtime packages are forbidden even from tests",
			pkgPath:    "field",
			testFile:   true,
			importPath: rootImport + "/runtime/encoder/json",
			wantReason: "runtime implementations",
		},
		{
			name:       "encoder cannot import field even from tests",
			pkgPath:    "encoder/encoders",
			testFile:   true,
			importPath: apiImport + "field",
			wantReason: "encoder packages",
		},
		{
			name:       "predicate may import core",
			pkgPath:    "predicate",
			importPath: apiImport + "core",
		},
		{
			name:       "predicate may import field",
			pkgPath:    "predicate",
			importPath: apiImport + "field",
		},
		{
			name:       "predicate cannot import level directly",
			pkgPath:    "predicate",
			importPath: apiImport + "level",
			wantReason: "predicate may depend",
		},
		{
			name:       "core cannot import predicate",
			pkgPath:    "core",
			importPath: apiImport + "predicate",
			wantReason: "core may depend",
		},
		{
			name:       "field may import encoder subpackages",
			pkgPath:    "field",
			importPath: apiImport + "encoder/encoders",
		},
		{
			name:       "buffer cannot import domain packages",
			pkgPath:    "buffer",
			importPath: apiImport + "field",
			wantReason: "buffer must stay",
		},
		{
			name:       "external tests may import public API packages",
			pkgPath:    "buffer",
			testFile:   true,
			importPath: apiImport + "field",
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			reason := forbiddenImportReason(tt.pkgPath, tt.testFile, tt.importPath)
			if tt.wantReason == "" {
				if reason != "" {
					t.Fatalf("forbiddenImportReason() = %q, want allowed import", reason)
				}
				return
			}
			if !strings.Contains(reason, tt.wantReason) {
				t.Fatalf("forbiddenImportReason() = %q, want substring %q", reason, tt.wantReason)
			}
		})
	}
}

func TestIsGeneratedGoFile(t *testing.T) {
	t.Parallel()

	generated := filepath.Join(t.TempDir(), "generated.go")
	if err := os.WriteFile(generated, []byte("// Code generated by test. DO NOT EDIT.\npackage importtest\n"), 0o600); err != nil {
		t.Fatalf("write generated file: %v", err)
	}
	if !isGeneratedGoFile(generated) {
		t.Fatal("isGeneratedGoFile(generated.go) = false, want true")
	}

	manual := filepath.Join(t.TempDir(), "manual.go")
	if err := os.WriteFile(manual, []byte("package importtest\n"), 0o600); err != nil {
		t.Fatalf("write manual file: %v", err)
	}
	if isGeneratedGoFile(manual) {
		t.Fatal("isGeneratedGoFile(manual.go) = true, want false")
	}
}

// checkFileImports validates one source file against the API dependency model.
//
// Tests are allowed to import public API packages as external users, except for
// the encoder-to-field prohibition. Production files are checked against
// package-specific rules so accidental convenience imports fail before they
// become part of the extension contract.
func checkFileImports(t *testing.T, apiDir, path string) {
	t.Helper()

	file, err := parser.ParseFile(token.NewFileSet(), path, nil, parser.ImportsOnly)
	if err != nil {
		t.Fatalf("parse imports in %s: %v", path, err)
	}

	pkgPath := apiPackage(apiDir, path)
	testFile := strings.HasSuffix(path, "_test.go")
	rel := apiRelativePath(apiDir, path)

	for _, imported := range file.Imports {
		importPath := strings.Trim(imported.Path.Value, `"`)
		if reason := forbiddenImportReason(pkgPath, testFile, importPath); reason != "" {
			t.Errorf("%s imports %q: %s", rel, importPath, reason)
		}
	}
}

// forbiddenImportReason returns a human-readable contract violation for a single
// import edge. An empty reason means the edge is allowed.
//
// The rules are intentionally explicit instead of graph-derived. API boundaries
// are part of the public design, and keeping each package's allowed neighbors in
// this table makes future API-layer changes reviewable.
func forbiddenImportReason(pkgPath string, testFile bool, importPath string) string {
	if importPath == rootImport {
		return "api packages must not import the root facade"
	}
	if strings.HasPrefix(importPath, rootImport+"/runtime/") {
		return "runtime implementations belong outside api packages"
	}
	if strings.HasPrefix(importPath, rootImport+"/internal/") {
		return "api packages must not depend on repository-internal implementation packages"
	}

	if !strings.HasPrefix(importPath, apiImport) {
		return ""
	}

	if isPackageOrSubpackage(pkgPath, "encoder") && isAPIImport(importPath, "field") {
		return "encoder packages must not import field; the API direction is field -> encoder -> buffer"
	}
	if testFile {
		return ""
	}

	switch {
	case pkgPath == "":
		if isAPIImportPath(importPath) {
			return "the root api package must remain only package documentation"
		}
	case pkgPath == "buffer":
		if isAPIImportPath(importPath) {
			return "buffer must stay below domain API packages"
		}
	case pkgPath == "caller":
		if !isAllowedAPIImport(importPath, "buffer") {
			return "caller may depend only on buffer for returned-buffer encoder contracts"
		}
	case pkgPath == "core":
		if !isAllowedAPIImport(importPath, "caller", "field", "level", "stack") {
			return "core may depend on value packages only; predicates, hooks, encoders, and writers stay outside core"
		}
	case pkgPath == "entrykey":
		if isAPIImportPath(importPath) {
			return "entrykey is a key vocabulary package and must not depend on other api packages"
		}
	case isPackageOrSubpackage(pkgPath, "encoder"):
		if !isAllowedAPIImport(importPath, "buffer", "encoder") {
			return "encoder packages may depend only on buffer and sibling encoder contracts"
		}
	case pkgPath == "field":
		if !isAllowedAPIImport(importPath, "buffer", "encoder") {
			return "field may depend only on encoder and buffer"
		}
	case pkgPath == "level":
		if !isAllowedAPIImport(importPath, "buffer") {
			return "level may depend only on buffer for value-specific encoding contracts"
		}
	case pkgPath == "predicate":
		if !isAllowedAPIImport(importPath, "core", "field") {
			return "predicate may depend only on core entry metadata and field values"
		}
	case pkgPath == "stack":
		if !isAllowedAPIImport(importPath, "buffer", "caller") {
			return "stack may depend only on caller values and buffer encoder contracts"
		}
	case pkgPath == "writer":
		if isAPIImportPath(importPath) {
			return "writer is a sink-contract package and must not depend on other api packages"
		}
	}

	return ""
}

// apiPackage returns the package path below api, such as "buffer" or
// "encoder/custom". The root api documentation package is represented as an
// empty string because it should not contain production imports.
func apiPackage(apiDir, path string) string {
	rel, err := filepath.Rel(apiDir, path)
	if err != nil {
		return ""
	}

	dir := filepath.ToSlash(filepath.Dir(rel))
	if dir == "." {
		return ""
	}

	return dir
}

// apiRelativePath formats paths in test failures relative to api so boundary
// errors stay short and portable across working directories.
func apiRelativePath(apiDir, path string) string {
	rel, err := filepath.Rel(apiDir, path)
	if err != nil {
		return path
	}

	return filepath.ToSlash(rel)
}

func isAPIImportPath(importPath string) bool {
	return strings.HasPrefix(importPath, apiImport)
}

func isAPIImport(importPath, pkgPath string) bool {
	prefix := apiImport + pkgPath

	return importPath == prefix || strings.HasPrefix(importPath, prefix+"/")
}

func isAllowedAPIImport(importPath string, allowedPkgPaths ...string) bool {
	for _, allowed := range allowedPkgPaths {
		if isAPIImport(importPath, allowed) {
			return true
		}
	}

	return false
}

func isPackageOrSubpackage(pkgPath, base string) bool {
	return pkgPath == base || strings.HasPrefix(pkgPath, base+"/")
}

// isGeneratedGoFile follows the standard "Code generated ... DO NOT EDIT."
// convention. Generated files are skipped because dependency policy should be
// enforced at the generator or source template, not against transient output.
func isGeneratedGoFile(path string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}

	const scanLimit = 2048
	if len(data) > scanLimit {
		data = data[:scanLimit]
	}

	text := string(data)
	return strings.Contains(text, "Code generated") &&
		strings.Contains(text, "DO NOT EDIT")
}

func repoRoot(t *testing.T) string {
	t.Helper()

	dir, err := filepath.Abs(".")
	if err != nil {
		t.Fatalf("resolve working directory: %v", err)
	}

	for {
		if exists(filepath.Join(dir, "go.mod")) {
			return dir
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("could not find repository root")
		}
		dir = parent
	}
}

func exists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}
